log_file: ./data/pullrequestcommentanalyzer.log

error_alert_sound_file: ./assets/ComputerErrorAlert.mp3 # From http://soundbible.com/1540-Computer-Error-Alert.html, CC BY 3.0

bigquery:
  pull_request_comments_results_csv_file: ./data/sample/ghtorrent_bigquery_result.csv

machine_learning:
  trained_excel_file: 

ghtorrent_mongodb:
  host: dutihr.st.ewi.tudelft.nl
  port: 27017
  database: github
  username: ghtorrentro
  password: ghtorrentro
  ssh_tunnel_host: dutihr.st.ewi.tudelft.nl
  ssh_tunnel_port: 22
  ssh_username: ghtorrent
  ssh_private_key: /Users/eddiechiang/.ssh/id_rsa
  ssh_private_key_password:

dialogue_act_classification:
  train_classifier: False # Whether to train/retrain Dialogue Act Classifier.
  trained_classifier_file: ./data/trained_dialogue_act_classifier.pickle
  test_set_percentage: 10 # Percentage of the labeled NPS Chat Corpus to be used as the test set (remainder will be the train set).

github:
  requests_cache_file: ./data/github_cache
  personal_access_tokens:
    - 