log_file: ./Thesis/Assets/pullrequestcommentanalyzer.log

# Whether to classify dialogue act type on GH Torrent Pull Request Comments data?
perform_dialogue_act_classification: False

dialogue_act_classification:
  train_classifier: False # Whether to train/retrain Dialogue Act Classifier.
  trained_classifier_file: ./Thesis/Assets/trained_dialogue_act_classifier.pickle
  test_set_percentage: 10 # Percentage of the labeled NPS Chat Corpus to be used as the test set (remainder will be the train set).
  pull_request_comments_csv_file: ./Thesis/Assets/results-20181214-113936.csv
  classified_output_csv_file: ./Thesis/Assets/results-20181214-113936-nlp-classified-output.csv
  # TODO: add percentage of the training.